<header>
    <nav>
        <ul>
            <li class="<?php if($page=='home'){echo 'active';}?>"><a href="index.php">Home</a></li>
			<li class="<?php if($page=='add'){echo 'active';}?>"><a href="addSales.php">Add Sales</a></li>
			<li class="<?php if($page=='edit'){echo 'active';}?>"><a href="editSales.php">Edit Sales</a></li>
			<li class="<?php if($page=='display'){echo 'active';}?>"><a href="displaySales.php">Display Sales</a></li>
            <li class="<?php if($page=='about'){echo 'active';}?>"><a href="aboutUs.php">About Us</a></li>
        </ul>
    </nav>
</header>